name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Build Electron App
      run: npm run build

    - name: Package App for Windows
      run: npx electron-builder --win --x64

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v3.x
      with:
        name: windows-build
        path: dist/*.exe
